# Generated by Django 2.2.4 on 2019-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAllo',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_value', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('category_url', models.TextField()),
                ('category_shop_id', models.IntegerField()),
            ],
            options={
                'db_table': 'category_allo',
            },
        ),
        migrations.CreateModel(
            name='CategoryEldorado',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_value', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('category_url', models.TextField()),
                ('category_shop_id', models.IntegerField()),
            ],
            options={
                'db_table': 'category_eldorado',
            },
        ),
        migrations.CreateModel(
            name='CategoryMoyo',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_value', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('category_url', models.TextField()),
                ('category_shop_id', models.IntegerField()),
            ],
            options={
                'db_table': 'category_moyo',
            },
        ),
    ]
