# Generated by Django 2.2.4 on 2019-08-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_value', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('category_url', models.TextField()),
                ('category_shop_id', models.IntegerField()),
            ],
        ),
    ]
