# Generated by Django 2.2.4 on 2019-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_shop_id', models.IntegerField()),
                ('product_title', models.TextField()),
                ('product_description', models.TextField(blank=True)),
            ],
        ),
    ]
