# Generated by Django 2.2.4 on 2019-08-06 20:21

from django.db import migrations, models
import djongo.models.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOPShops',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_url', models.TextField()),
                ('shop_tags', djongo.models.fields.ArrayModelField(model_container=products.models.ShopTags)),
            ],
        ),
    ]
