# Generated by Django 2.2.4 on 2019-08-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190806_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TOPShops',
            new_name='MyShops',
        ),
    ]
