# Generated by Django 2.2.4 on 2019-08-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190806_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyShops',
            new_name='Shops',
        ),
    ]
