# Generated by Django 2.2.4 on 2019-08-18 11:38

from django.db import migrations, models
import djongo.models.fields
import shops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('shop_headers', models.TextField()),
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_url', models.TextField()),
                ('shop_card_tags', djongo.models.fields.ArrayModelField(model_container=shops.models.ShopTags)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
